import type { WebsitePlan } from './website.js';

// Authored example based on the accepted Canvas repository contract. No model
// invocation, site capture, customer approval or media generation is implied.
export function websiteDirectionDemo(): WebsitePlan {
  const workshopPage = [
    { sectionId: 'hero', copy: 'Edit a direction with the sources beside it.\n\nStart with a project note and a reference worth keeping. Arrange that context in the canvas, then write the direction you want to pursue. Read the source material beside your revisions.\n\nArranging and editing the plan works without a model key. If you add model-generated copy, review it against the same sources before using it.', action: 'Open the canvas workspace' },
    { sectionId: 'proof', copy: 'Try one small piece of work.\n\nThis authored page plan starts from the Canvas repository contract. The contract is the source; the direction is a paragraph you can revise.\n\nSave your edits and choose the direction you reviewed. That choice captures a checkpoint of the saved plan. Export the selected implementation brief as JSON or Markdown. It carries the reviewed copy, source reference, proposed files and questions still to resolve.\n\nA site capture and a customer result have not been attached to this example.', action: 'Review the page plan and its source' },
    { sectionId: 'handoff', copy: 'Give the build a specific starting point.\n\nRead the exported brief before passing it to Codex or Claude. Check the copy, repository target and proposed files, then decide which unresolved questions the agent should address.\n\nExporting a brief does not start an agent or change a repository. You choose when to take the next step.', action: 'Export the reviewed implementation brief' },
  ];
  return {
    version: 'starlight.websitePlan.v1', id: 'canvas-website-study', title: 'A place to turn context into finished work', origin: 'authored_example',
    snapshot: {
      id: 'canvas-source-contract',
      source: { kind: 'repository', repository: 'https://github.com/frankxai/starlight-agent-canvas', branch: 'main', commit: '1b49d4202cc555c0c5f1f362bf2bfe5bf0d2f7ff' },
      observedAt: '2026-10-07T12:06:28.726Z', method: 'repository_reference',
      notes: 'At main1b49d42, AGENTS.md requires a usable canvas first, local files, optional provider keys and safe explicit MCP tools. The website workbench supports editable authored directions, source-linked graph views, browser-tab draft recovery, hash-guarded canonical saving and explicit checkpoint choice. Editing, saving and export work without API keys. A chosen direction exports a read-only JSON or Markdown implementation brief containing the source, selected checkpoint/hash, page copy, target repository, proposed routes/files and unresolved evidence. Export does not start an agent, mutate another repository or publish a site. Source inspection does not establish live model generation, site capture, customer approval or commercial results. These three complete authored alternatives propose a separate /about page without replacing the canvas workspace.',
      views: [
        { viewport: 'desktop', width: 1440, height: 900, status: 'reference_only', notes: 'Repository observation only. Attach an actual desktop capture before implementing a visual redesign.' },
        { viewport: 'mobile', width: 390, height: 844, status: 'reference_only', notes: 'Repository observation only. Attach an actual mobile capture; no image was generated or imported.' },
      ],
    },
    brief: {
      audience: 'Founders and creators who move evidence between their browser, notes and coding agents.',
      job: 'Explain one useful journey: bring sources together, edit a direction, preserve a reviewed state and carry scoped context into Codex or Claude.',
      outcome: 'A visitor understands the artifact they will make and can open the existing local workspace.',
      copyConstraints: 'Use concrete inputs and outputs. Separate keyless arrangement from optional model generation. Avoid revenue promises and invented customer proof.',
      accessibilityConstraints: 'Keyboard and touch access, readable long copy, visible focus, descriptive links, reduced motion and source alternatives for images.',
      productConstraints: 'Keep the first screen as the canvas. Use a separate /about route for this proposed page. Local-first v0.1; no auth, payments, hosted sync or external mutation.',
    },
    target: { status: 'resolved', repository: 'https://github.com/frankxai/starlight-agent-canvas', issueUrl: 'https://github.com/frankxai/starlight-agent-canvas/issues/27' },
    options: [
      { id: 'workshop', title: 'The open workshop', premise: 'Follow one piece of work from a source note to an edited direction and a checkpoint-linked implementation brief. The page example is authored and its missing captures remain explicit.', headline: 'Edit a direction with the sources beside it.', body: 'Bring a project note and a useful reference into the canvas. Write a direction, review it against the source material and export the copy you chose for the build.', action: 'Open the canvas', tradeoff: 'A single walkthrough makes the sequence clear, but a real example is needed to demonstrate the outcome beyond this authored page plan.', sectionCopy: workshopPage, sourceQuotes: ['Editing, saving and export work without API keys.', 'A chosen direction exports a read-only JSON or Markdown implementation brief'] },
      { id: 'constellation', title: 'The connected studio', premise: 'Begin with the relationship between a decision and its evidence. The visitor inspects a source-linked plan before considering the implementation handoff; the graph has a readable inspector alternative.', headline: 'See the sources behind a direction.', body: 'Keep the original reference, revised words and implementation details together. Inspect what supports the direction, make the gaps clear and choose the context you want to carry forward.', action: 'Start with your sources', tradeoff: 'Connections help explain the decision, but a graph alone can hide the reading order. The same evidence must remain available through the inspector.', sourceQuotes: ['The website workbench supports editable authored directions, source-linked graph views', 'Export does not start an agent, mutate another repository or publish a site.'], sectionCopy: [
        { sectionId: 'hero', copy: 'See the sources behind a direction.\n\nA paragraph makes more sense when you can read what it came from. Keep a source reference beside your edited wording and inspect how it relates to the page you want to build.\n\nThis arrangement needs no model key. Optional generated copy belongs in the same review: its wording must still be checked against the retained source.', action: 'Inspect a source-linked direction' },
        { sectionId: 'proof', copy: 'Read the connection before making the choice.\n\nIn this authored example, the repository contract is the source for a proposed Canvas information page. The plan links that source to a direction, page sections and a target repository.\n\nUse the readable inspector to check the copy, route, proposed files and open questions. Choose the saved direction once the evidence and wording agree. The choice records a checkpoint of the reviewed state.\n\nThe graph and inspector organize the same plan; neither supplies a missing site capture or customer result.', action: 'Read the direction in the inspector' },
        { sectionId: 'handoff', copy: 'Keep the evidence in the implementation brief.\n\nDownload the chosen direction as JSON when a tool needs structured fields, or as Markdown when you want to read it through. The brief carries the source and selected checkpoint with the proposed page sections and unresolved evidence.\n\nInspect the target and scope before sharing the file with a coding agent. The export itself is read-only.', action: 'Download the selected JSON or Markdown brief' },
      ] },
      { id: 'field-notes', title: 'The founder’s field notes', premise: 'Start with the moment a founder returns to unfinished work. The page explains what a saved plan and reviewed checkpoint preserve, while stating the limits of browser-tab recovery.', headline: 'Pick up the direction you saved.', body: 'Return to the words, sources and decision you kept for the build. A saved plan gives you a clear starting point; a reviewed checkpoint lets the handoff refer to a particular state.', action: 'Plan your next build', tradeoff: 'Continuity speaks to a recurring problem, but recovery needs careful language: tab storage is not cross-device backup and a checkpoint is not release approval.', sourceQuotes: ['browser-tab draft recovery, hash-guarded canonical saving and explicit checkpoint choice.', 'A chosen direction exports a read-only JSON or Markdown implementation brief'], sectionCopy: [
        { sectionId: 'hero', copy: 'Pick up the direction you saved.\n\nWhen you return to a page plan, start with its words and source references. Read the direction you kept, then decide what needs another edit before the build.\n\nSaving and reviewing this plan require no model key. If you later add generated wording, treat it as a new draft to check before making a choice.', action: 'Open the saved website plan' },
        { sectionId: 'proof', copy: 'Keep a reviewed state you can refer to.\n\nThis authored example begins with the Canvas repository contract and a proposed page direction. Save the plan, review its source and copy, then choose the direction to capture that state in a checkpoint.\n\nNew edits need a new review. The saved choice identifies the version used for an implementation brief; it does not approve a release.\n\nUnsaved text can recover in the same browser tab. Save or download work you want to keep; tab storage is not a cross-device backup.', action: 'Save the plan and review the direction' },
        { sectionId: 'handoff', copy: 'Make the next handoff refer to the right version.\n\nBefore a build, choose the saved direction and read its exported implementation brief. It names the source, checkpoint and plan hash along with the proposed page copy and files.\n\nKeep that file with the work you pass to Codex or Claude, so the next reader can see which reviewed state the brief describes. Unresolved evidence stays visible.', action: 'Export the checkpoint-linked implementation brief' },
      ] },
    ],
    sections: [
      { id: 'hero', label: 'A useful first promise', kind: 'page_section', route: '/about', action: workshopPage[0]!.action, why: 'Let the visitor recognize their own scattered source problem and see the editable output.', copy: workshopPage[0]!.copy, responsive: 'Stack promise, action and source/artifact example on mobile. Keep the primary action visible without a carousel.', files: ['apps/web/app/about/page.tsx'], acceptance: ['Root / continues to show the usable workspace.', 'The primary CTA links to / and opens no external application automatically.'], accessibility: ['Use one page heading and descriptive action text.', 'Provide the same example in text when media is unavailable.'] },
      { id: 'proof', label: 'Trace a proposed page direction', kind: 'funnel_step', route: '/about', action: workshopPage[1]!.action, why: 'Ground the promise in an artifact and a recoverable decision.', copy: workshopPage[1]!.copy, responsive: 'Use a vertical sequence on mobile and a three-column source/direction/handoff arrangement on desktop.', files: ['apps/web/app/about/page.tsx'], acceptance: ['Example cites its source revision and labels authored content.', 'Show an actual export and reload result before claiming workflow success.'], accessibility: ['Sequence order remains readable without spatial layout.', 'Use captions and alt text for any later screenshots.'] },
      { id: 'handoff', label: 'Carry the decision into the build', kind: 'cta', route: '/about', action: workshopPage[2]!.action, why: 'Show the bridge into tools the founder already uses.', copy: workshopPage[2]!.copy, responsive: 'Keep download and copy actions separate, with a visible failure/retry message.', files: ['apps/web/app/about/page.tsx'], acceptance: ['Export is read-only and does not deploy, publish or run an agent.', 'All unresolved evidence remains visible in the packet.'], accessibility: ['Download links describe their file format.', 'Announce copy status and preserve keyboard focus.'] },
    ],
    assets: [],
  };
}
